# Generated by Django 6.0.2 on 2026-02-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('skin_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('face_shape', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
