# Generated by Django 6.0.2 on 2026-04-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_personauser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='personauser',
            name='undertone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
